### PR TITLE
Test9

### PR DESCRIPTION
**Pull request by tim9413**

### CODE REVIEW

**Comment by dmh** [comment]
Hey,
We need a correct commit message here:
https://github.com/t3kit/t3kit/blob/master/CONTRIBUTING.md

**Comment by tim9413** [comment]
> Hey,
> We need a correct commit message here:
> https://github.com/t3kit/t3kit/blob/master/CONTRIBUTING.md

@dmh Do you mean "[TASK] Change package name" should be "[BUGFIX] change package name"?

**Review by mabolek — APPROVED** [review]

**Comment by mabolek** [comment]
@tim9413 I think that's what @dmh means. In any case: It sounds like a good thing to make that change.

**Comment by dmh** [comment]
Hey guys @mabolek @tim9413 
Sorry for the misunderstanding. 
I meant `PR message` not `commit message`.
We need to have well formatted and understandable changelog based on 'git log', for this we need to use option 'Squash and merge' instead of just 'Merge' for merging Pull-Requests, and in case of 'Squash and merge', commit message will be consist of 'PR message' and here we have 'test9' which is wrong.

**Comment by tim9413** [comment]
Is it too late to change the branch name and PR message?

**Comment by dmh** [comment]
It is not too late, but I would skip it, let it be like it is. 
Keep this info for future Pull-Requests.

**Comment by mabolek** [comment]
Duly noted.

**Comment by tim9413** [comment]
Okey

**Pull request merged**
