### PR TITLE
[TASK] Make it work with tt_address v4 and up

### PR DESCRIPTION
**Pull request by BastianBalthasarBux**
Resolves issue #25

### CODE REVIEW

**Comment by anjeylink** [comment]
@BastianBalthasarBux new version won't support tt_address

**Comment by BastianBalthasarBux** [comment]
What a pitty. So I will have to develop my own Newsletter Subscription, which supports both, tt_address and fe_users ...

**Comment by anjeylink** [comment]
you can configure extbase settings to save subscription in  tt_address table.

**Comment by BastianBalthasarBux** [comment]
Thanks for the hint, I already thought about it, after reading your code.

**Pull request closed without merging**
